//! Integration tests for fatxlib.
//!
//! These tests use file-backed FATX/XTAF images generated by fatx-mkimage.
//! No hardware required — all tests use temporary image files.

mod common;

use std::cell::RefCell;
use std::io::{Cursor, Read, Seek, SeekFrom, Write};
use std::rc::Rc;
use std::thread::sleep;
use std::time::Duration;

use fatxlib::error::FatxError;
use fatxlib::types::*;
use fatxlib::volume::FatxVolume;

#[derive(Default)]
struct FailingWriteState {
    fail_on_write: Option<usize>,
    writes_seen: usize,
}

struct FailingWriteCursor {
    inner: Cursor<Vec<u8>>,
    state: Rc<RefCell<FailingWriteState>>,
}

impl Read for FailingWriteCursor {
    fn read(&mut self, buf: &mut [u8]) -> std::io::Result<usize> {
        self.inner.read(buf)
    }
}

impl Seek for FailingWriteCursor {
    fn seek(&mut self, pos: SeekFrom) -> std::io::Result<u64> {
        self.inner.seek(pos)
    }
}

impl Write for FailingWriteCursor {
    fn write(&mut self, buf: &[u8]) -> std::io::Result<usize> {
        let mut state = self.state.borrow_mut();
        state.writes_seen += 1;
        if state.fail_on_write == Some(state.writes_seen) {
            return Err(std::io::Error::other("injected write failure"));
        }
        self.inner.write(buf)
    }

    fn flush(&mut self) -> std::io::Result<()> {
        self.inner.flush()
    }
}

// ===========================================================================
// Volume open / basics
// ===========================================================================

#[test]
fn test_open_volume() {
    let (_tmp, vol) = common::create_fatx_image(2);
    assert!(vol.superblock.is_valid());
    assert!(
        vol.superblock.volume_id != 0,
        "volume ID should be non-zero"
    );
    assert_eq!(vol.superblock.sectors_per_cluster, 32);
    assert_eq!(vol.fat_type, FatType::Fat16);
}

#[test]
fn test_open_xtaf_volume() {
    let (_tmp, vol) = common::create_xtaf_image(2);
    assert!(vol.superblock.is_valid());
    assert_eq!(&vol.superblock.magic, b"XTAF");
    assert!(
        vol.superblock.volume_id != 0,
        "volume ID should be non-zero"
    );
    assert_eq!(vol.fat_type, FatType::Fat16);
}

#[test]
fn test_open_volume_with_offset() {
    // Embed a FATX image at a non-zero offset (simulating a partition)
    use std::io::{Read, Write};

    let (_tmp, _vol) = common::create_fatx_image(2);
    let img_path = common::image_path(&_tmp);
    drop(_vol); // close the volume so we can read the raw file

    let mut raw = Vec::new();
    std::fs::File::open(&img_path)
        .unwrap()
        .read_to_end(&mut raw)
        .unwrap();

    let offset = 0x10000usize; // 64 KB offset
    let tmp_dir = tempfile::TempDir::new().unwrap();
    let padded_path = tmp_dir.path().join("padded.img");
    {
        let mut f = std::fs::File::create(&padded_path).unwrap();
        f.write_all(&vec![0u8; offset]).unwrap();
        f.write_all(&raw).unwrap();
    }

    let file = std::fs::OpenOptions::new()
        .read(true)
        .write(true)
        .open(&padded_path)
        .unwrap();
    let vol = FatxVolume::open(file, offset as u64, raw.len() as u64).expect("open with offset");
    assert!(vol.superblock.is_valid());
}

#[test]
fn test_invalid_magic_fails() {
    // Error tests use Cursor directly — they test rejection of invalid data
    let mut data = vec![0u8; 2 * 1024 * 1024];
    data[0..4].copy_from_slice(b"NOPE");
    let cursor = std::io::Cursor::new(data);
    assert!(FatxVolume::open(cursor, 0, 0).is_err());
}

#[test]
fn test_too_small_volume_fails() {
    let data = vec![0u8; 512]; // way too small
    let cursor = std::io::Cursor::new(data);
    assert!(FatxVolume::open(cursor, 0, 0).is_err());
}

// ===========================================================================
// Directory operations
// ===========================================================================

#[test]
fn test_read_empty_root() {
    let (_tmp, mut vol) = common::create_fatx_image(2);
    let entries = vol.read_root_directory().expect("Failed to read root dir");
    assert!(entries.is_empty(), "Root directory should be empty");
}

#[test]
fn test_create_directory() {
    let (_tmp, mut vol) = common::create_fatx_image(2);

    vol.create_directory("/saves").expect("mkdir");
    let entries = vol.read_root_directory().expect("readdir");
    assert_eq!(entries.len(), 1);
    assert!(entries[0].is_directory());
    assert_eq!(entries[0].filename(), "saves");
}

#[test]
fn test_create_nested_directories() {
    let (_tmp, mut vol) = common::create_fatx_image(4);

    vol.create_directory("/a").expect("mkdir a");
    vol.create_directory("/a/b").expect("mkdir a/b");
    vol.create_directory("/a/b/c").expect("mkdir a/b/c");

    let cluster = vol.resolve_path("/a/b").unwrap().first_cluster;
    let entries = vol.read_directory(cluster).expect("readdir a/b");
    assert_eq!(entries.len(), 1);
    assert_eq!(entries[0].filename(), "c");
}

#[test]
fn test_create_multiple_entries_in_directory() {
    let (_tmp, mut vol) = common::create_fatx_image(4);

    for i in 0..20 {
        let name = format!("/file_{:02}.txt", i);
        vol.create_file(&name, format!("data {}", i).as_bytes())
            .expect("create");
    }

    let entries = vol.read_root_directory().expect("readdir");
    assert_eq!(entries.len(), 20);
}

// ===========================================================================
// File operations
// ===========================================================================

#[test]
fn test_create_and_read_file() {
    let (_tmp, mut vol) = common::create_fatx_image(2);

    let test_data = b"Hello, Xbox FATX filesystem!";
    vol.create_file("/test.txt", test_data).expect("create");

    let read_data = vol.read_file_by_path("/test.txt").expect("read");
    assert_eq!(read_data, test_data);
}

#[test]
fn test_create_empty_file() {
    let (_tmp, mut vol) = common::create_fatx_image(2);

    vol.create_file("/empty.txt", &[]).expect("create empty");

    let read_data = vol.read_file_by_path("/empty.txt").expect("read");
    assert!(read_data.is_empty());
}

#[test]
fn test_create_file_in_subdirectory() {
    let (_tmp, mut vol) = common::create_fatx_image(2);

    vol.create_directory("/saves").expect("mkdir");
    let save_data = b"save game data here";
    vol.create_file("/saves/game1.sav", save_data)
        .expect("create");

    let read_data = vol.read_file_by_path("/saves/game1.sav").expect("read");
    assert_eq!(read_data, save_data);
}

#[test]
fn test_file_spanning_multiple_clusters() {
    // 16 KB clusters, so a 64 KB file spans 4 clusters
    let (_tmp, mut vol) = common::create_fatx_image(4);

    let big_data: Vec<u8> = (0..65536u32).map(|i| (i % 256) as u8).collect();
    vol.create_file("/big.bin", &big_data).expect("create big");

    let read_data = vol.read_file_by_path("/big.bin").expect("read big");
    assert_eq!(read_data.len(), 65536);
    assert_eq!(read_data, big_data);
}

#[test]
fn test_file_exact_cluster_size() {
    // File exactly 16384 bytes = 1 cluster
    let (_tmp, mut vol) = common::create_fatx_image(2);

    let data = vec![0xAB; 16384];
    vol.create_file("/exact.bin", &data).expect("create");

    let read = vol.read_file_by_path("/exact.bin").expect("read");
    assert_eq!(read.len(), 16384);
    assert_eq!(read, data);
}

#[test]
fn test_file_one_byte() {
    let (_tmp, mut vol) = common::create_fatx_image(2);

    vol.create_file("/one.bin", &[42]).expect("create");
    let read = vol.read_file_by_path("/one.bin").expect("read");
    assert_eq!(read, vec![42]);
}

#[test]
fn test_large_file_256kb() {
    let (_tmp, mut vol) = common::create_fatx_image(4);

    let data: Vec<u8> = (0..262144u32).map(|i| (i % 251) as u8).collect();
    vol.create_file("/large.bin", &data).expect("create");

    let read = vol.read_file_by_path("/large.bin").expect("read");
    assert_eq!(read.len(), 262144);
    assert_eq!(read, data);
}

#[test]
fn test_read_file_range_within_cluster() {
    let (_tmp, mut vol) = common::create_fatx_image(4);

    let data: Vec<u8> = (0..8192u32).map(|i| (i % 251) as u8).collect();
    vol.create_file("/range.bin", &data).expect("create");

    let entry = vol.resolve_path("/range.bin").expect("resolve");
    let read = vol.read_file_range(&entry, 123, 777).expect("range read");
    assert_eq!(read, data[123..900].to_vec());
}

#[test]
fn test_read_file_range_shared_across_clusters() {
    let (_tmp, mut vol) = common::create_fatx_image(4);

    let data: Vec<u8> = (0..65536u32).map(|i| (i % 241) as u8).collect();
    vol.create_file("/range-shared.bin", &data).expect("create");

    let entry = vol.resolve_path("/range-shared.bin").expect("resolve");
    let offset = 16_000u64;
    let count = 20_000usize;
    let read = vol
        .read_file_range_shared(&entry, offset, count)
        .expect("shared range read");
    assert_eq!(
        read,
        data[offset as usize..offset as usize + count].to_vec()
    );
}

// ===========================================================================
// Delete operations
// ===========================================================================

#[test]
fn test_delete_file() {
    let (_tmp, mut vol) = common::create_fatx_image(2);

    vol.create_file("/deleteme.txt", b"temporary data")
        .expect("create");
    assert_eq!(vol.read_root_directory().unwrap().len(), 1);

    vol.delete("/deleteme.txt").expect("delete");
    assert_eq!(vol.read_root_directory().unwrap().len(), 0);
}

#[test]
fn test_delete_empty_directory() {
    let (_tmp, mut vol) = common::create_fatx_image(2);

    vol.create_directory("/emptydir").expect("mkdir");
    vol.delete("/emptydir").expect("delete empty dir");
    assert_eq!(vol.read_root_directory().unwrap().len(), 0);
}

#[test]
fn test_delete_nonexistent_fails() {
    let (_tmp, mut vol) = common::create_fatx_image(2);

    assert!(vol.delete("/nonexistent.txt").is_err());
}

#[test]
fn test_delete_recursive() {
    let (_tmp, mut vol) = common::create_fatx_image(4);

    vol.create_directory("/parent").expect("mkdir");
    vol.create_directory("/parent/child").expect("mkdir child");
    vol.create_file("/parent/file.txt", b"data")
        .expect("create file");
    vol.create_file("/parent/child/nested.txt", b"nested")
        .expect("create nested");

    vol.delete_recursive("/parent").expect("delete recursive");
    assert_eq!(vol.read_root_directory().unwrap().len(), 0);
}

#[test]
fn test_delete_frees_clusters() {
    let (_tmp, mut vol) = common::create_fatx_image(4);

    let stats_before = vol.stats().expect("stats");
    let data = vec![0u8; 65536]; // 4 clusters
    vol.create_file("/temp.bin", &data).expect("create");

    let stats_during = vol.stats().expect("stats");
    assert!(stats_during.free_clusters < stats_before.free_clusters);

    vol.delete("/temp.bin").expect("delete");
    let stats_after = vol.stats().expect("stats");
    assert_eq!(stats_after.free_clusters, stats_before.free_clusters);
}

// ===========================================================================
// Rename operations
// ===========================================================================

#[test]
fn test_rename_file() {
    let (_tmp, mut vol) = common::create_fatx_image(2);

    vol.create_file("/old.txt", b"some data").expect("create");
    vol.rename("/old.txt", "new.txt").expect("rename");

    assert!(vol.resolve_path("/old.txt").is_err());
    let data = vol.read_file_by_path("/new.txt").expect("read renamed");
    assert_eq!(data, b"some data");
}

#[test]
fn test_rename_directory() {
    let (_tmp, mut vol) = common::create_fatx_image(4);

    vol.create_directory("/olddir").expect("mkdir");
    vol.create_file("/olddir/inside.txt", b"inside")
        .expect("create");

    vol.rename("/olddir", "newdir").expect("rename dir");

    assert!(vol.resolve_path("/olddir").is_err());
    let data = vol.read_file_by_path("/newdir/inside.txt").expect("read");
    assert_eq!(data, b"inside");
}

#[test]
fn test_rename_preserves_data() {
    let (_tmp, mut vol) = common::create_fatx_image(2);

    let original_data: Vec<u8> = (0..1024).map(|i| (i % 256) as u8).collect();
    vol.create_file("/before.bin", &original_data)
        .expect("create");
    vol.rename("/before.bin", "after.bin").expect("rename");

    let read = vol.read_file_by_path("/after.bin").expect("read");
    assert_eq!(read, original_data);
}

#[test]
fn test_rename_rejects_destination_collision() {
    let (_tmp, mut vol) = common::create_fatx_image(2);

    vol.create_file("/a.txt", b"aaa").expect("create a");
    vol.create_file("/b.txt", b"bbb").expect("create b");

    let result = vol.rename("/a.txt", "b.txt");
    assert!(
        matches!(result, Err(FatxError::FileExists(ref path)) if path == "/b.txt"),
        "expected destination collision, got {:?}",
        result
    );

    assert_eq!(vol.read_file_by_path("/a.txt").expect("read a"), b"aaa");
    assert_eq!(vol.read_file_by_path("/b.txt").expect("read b"), b"bbb");
}

#[test]
fn test_rename_same_name_is_noop() {
    let (_tmp, mut vol) = common::create_fatx_image(2);

    vol.create_file("/a.txt", b"payload").expect("create");
    vol.rename("/a.txt", "a.txt").expect("rename noop");

    assert_eq!(
        vol.read_file_by_path("/a.txt").expect("read after noop"),
        b"payload"
    );
}

#[test]
fn test_rename_case_only_changes_filename() {
    let (_tmp, mut vol) = common::create_fatx_image(2);

    vol.create_file("/a.txt", b"payload").expect("create");
    vol.rename("/a.txt", "A.TXT").expect("rename case-only");

    let entry = vol.resolve_path("/A.TXT").expect("resolve renamed");
    assert_eq!(entry.filename(), "A.TXT");
    assert_eq!(
        vol.read_file_by_path("/A.TXT").expect("read renamed"),
        b"payload"
    );
}

// ===========================================================================
// Volume stats
// ===========================================================================

#[test]
fn test_volume_stats() {
    let (_tmp, vol) = common::create_fatx_image(2);

    let stats = vol.stats().expect("stats");
    assert!(stats.total_clusters > 0);
    assert!(stats.free_clusters > 0);
    assert_eq!(stats.bad_clusters, 0);
    // Root directory uses 1 cluster
    assert_eq!(
        stats.total_clusters - stats.free_clusters,
        1, // just root dir
        "Only root cluster should be used on empty volume"
    );
}

#[test]
fn test_stats_after_writes() {
    let (_tmp, mut vol) = common::create_fatx_image(4);

    let initial = vol.stats().expect("stats");
    let data = vec![0u8; 16384 * 5]; // 5 clusters
    vol.create_file("/big.bin", &data).expect("create");

    let after = vol.stats().expect("stats");
    // Used clusters increased by at least 5 (file) + possibly 0 (root already counted)
    assert!(after.free_clusters < initial.free_clusters);
}

// ===========================================================================
// Filename validation and edge cases
// ===========================================================================

#[test]
fn test_filename_too_long() {
    let (_tmp, mut vol) = common::create_fatx_image(2);

    let long_name = "/".to_string() + &"a".repeat(50); // >42 chars
    assert!(vol.create_file(&long_name, b"data").is_err());
}

#[test]
fn test_filename_max_length() {
    let (_tmp, mut vol) = common::create_fatx_image(2);

    let name = "/".to_string() + &"x".repeat(42); // exactly 42 chars
    vol.create_file(&name, b"data")
        .expect("create 42-char name");

    let entries = vol.read_root_directory().expect("readdir");
    assert_eq!(entries.len(), 1);
    assert_eq!(entries[0].filename().len(), 42);
}

#[test]
fn test_case_insensitive_lookup() {
    let (_tmp, mut vol) = common::create_fatx_image(2);

    vol.create_file("/Hello.TXT", b"data").expect("create");

    // These should all resolve (FATX is case-insensitive for lookup)
    assert!(vol.resolve_path("/Hello.TXT").is_ok());
    assert!(vol.resolve_path("/hello.txt").is_ok());
    assert!(vol.resolve_path("/HELLO.TXT").is_ok());
}

#[test]
fn test_resolve_nonexistent_path() {
    let (_tmp, mut vol) = common::create_fatx_image(2);

    assert!(vol.resolve_path("/does_not_exist").is_err());
    assert!(vol.resolve_path("/a/b/c").is_err());
}

// ===========================================================================
// Timestamp encoding/decoding
// ===========================================================================

#[test]
fn test_timestamp_roundtrip() {
    let date = DirectoryEntry::encode_date(2024, 3, 15);
    let (y, m, d) = DirectoryEntry::decode_date(date);
    assert_eq!((y, m, d), (2024, 3, 15));

    let time = DirectoryEntry::encode_time(14, 30, 22);
    let (h, min, s) = DirectoryEntry::decode_time(time);
    assert_eq!((h, min, s), (14, 30, 22));
}

#[test]
fn test_timestamp_boundary_values() {
    // Minimum date: 1980-01-01
    let date = DirectoryEntry::encode_date(1980, 1, 1);
    let (y, m, d) = DirectoryEntry::decode_date(date);
    assert_eq!((y, m, d), (1980, 1, 1));

    // Midnight
    let time = DirectoryEntry::encode_time(0, 0, 0);
    let (h, min, s) = DirectoryEntry::decode_time(time);
    assert_eq!((h, min, s), (0, 0, 0));

    // End of day
    let time = DirectoryEntry::encode_time(23, 59, 58);
    let (h, min, s) = DirectoryEntry::decode_time(time);
    assert_eq!((h, min, s), (23, 59, 58));
}

// ===========================================================================
// XTAF (Xbox 360) format tests
// ===========================================================================

#[test]
fn test_xtaf_create_and_read_file() {
    let (_tmp, mut vol) = common::create_xtaf_image(2);

    let data = b"Xbox 360 XTAF test data!";
    vol.create_file("/test360.txt", data).expect("create");

    let read = vol.read_file_by_path("/test360.txt").expect("read");
    assert_eq!(read, data);
}

#[test]
fn test_xtaf_directory_operations() {
    let (_tmp, mut vol) = common::create_xtaf_image(4);

    vol.create_directory("/Content").expect("mkdir");
    vol.create_file("/Content/game.bin", b"game data")
        .expect("create");

    let cluster = vol.resolve_path("/Content").unwrap().first_cluster;
    let entries = vol.read_directory(cluster).expect("readdir");
    assert_eq!(entries.len(), 1);
    assert_eq!(entries[0].filename(), "game.bin");
}

#[test]
fn test_xtaf_delete_and_stats() {
    let (_tmp, mut vol) = common::create_xtaf_image(4);

    let stats_before = vol.stats().expect("stats");
    vol.create_file("/temp.bin", &vec![0u8; 32768])
        .expect("create");
    vol.delete("/temp.bin").expect("delete");

    let stats_after = vol.stats().expect("stats");
    assert_eq!(stats_after.free_clusters, stats_before.free_clusters);
}

// ===========================================================================
// Stress / fill tests
// ===========================================================================

#[test]
fn test_fill_root_directory() {
    // Fill root dir with many small files — tests directory entry packing
    let (_tmp, mut vol) = common::create_fatx_image(4);

    // Each dir entry is 64 bytes. One 16 KB cluster fits 256 entries.
    // Create 100 files — well within one cluster.
    for i in 0..100 {
        let name = format!("/f{:04}.dat", i);
        vol.create_file(&name, &[i as u8; 4]).expect("create");
    }

    let entries = vol.read_root_directory().expect("readdir");
    assert_eq!(entries.len(), 100);

    // Verify a sampling of files
    for i in [0, 49, 99] {
        let name = format!("/f{:04}.dat", i);
        let data = vol.read_file_by_path(&name).expect("read");
        assert_eq!(data, vec![i as u8; 4]);
    }
}

#[test]
fn test_create_delete_create_reuses_space() {
    let (_tmp, mut vol) = common::create_fatx_image(2);

    // Fill and delete repeatedly
    for _ in 0..5 {
        vol.create_file("/cycle.bin", &vec![0xAA; 16384])
            .expect("create");
        vol.delete("/cycle.bin").expect("delete");
    }

    // Should still have space — clusters were freed each time
    let stats = vol.stats().expect("stats");
    assert!(stats.free_clusters > 0);

    // Final create should succeed
    vol.create_file("/final.bin", b"still works")
        .expect("create final");
    let data = vol.read_file_by_path("/final.bin").expect("read");
    assert_eq!(data, b"still works");
}

// ===========================================================================
// FAT chain operations
// ===========================================================================

#[test]
fn test_chain_allocation_and_read() {
    let (_tmp, mut vol) = common::create_fatx_image(4);

    // Create a file that spans 3 clusters (48 KB)
    let data = vec![0xBB; 16384 * 3];
    vol.create_file("/chain.bin", &data).expect("create");

    // Read back and verify
    let entry = vol.resolve_path("/chain.bin").expect("resolve");
    let chain = vol.read_chain(entry.first_cluster).expect("read chain");
    assert_eq!(chain.len(), 3, "Should be exactly 3 clusters in chain");

    let read = vol.read_file(&entry).expect("read file");
    assert_eq!(read, data);
}

// ===========================================================================
// Flush / persistence
// ===========================================================================

#[test]
fn test_flush_persists_fat() {
    let (_tmp, mut vol) = common::create_fatx_image(2);

    vol.create_file("/persist.txt", b"persistent data")
        .expect("create");
    vol.flush().expect("flush");

    // The FAT should be dirty=false after flush
    // We can verify by reading the file back (it depends on the FAT being correct)
    let data = vol.read_file_by_path("/persist.txt").expect("read");
    assert_eq!(data, b"persistent data");
}

// ===========================================================================
// Deep recursive directory deletion (1–10 layers)
// ===========================================================================

/// Regression test for Finder directory deletion.
/// Finder sends a single NFS remove for a non-empty directory. The NFS layer
/// falls back to delete_recursive, which must handle arbitrarily deep trees.
/// This test builds nested directories from 1 to 10 levels deep, each with a
/// file at every level, then verifies delete_recursive removes everything and
/// frees all clusters.
#[test]
fn test_delete_recursive_deep_1_to_10_layers() {
    // Use a larger image — deep trees with files at every level need space
    let (_tmp, mut vol) = common::create_fatx_image(8);

    for depth in 1..=10 {
        // Build the nested path: /d1/d2/d3/.../dN
        let mut dir_path = String::new();
        for level in 1..=depth {
            dir_path.push_str(&format!("/d{}", level));
            vol.create_directory(&dir_path)
                .unwrap_or_else(|_| panic!("mkdir {} (depth={})", dir_path, depth));

            // Put a file at every level so delete_recursive must handle mixed content
            let file_path = format!("{}/f{}.bin", dir_path, level);
            let data = vec![level as u8; 256]; // small file with recognizable content
            vol.create_file(&file_path, &data)
                .unwrap_or_else(|_| panic!("create {} (depth={})", file_path, depth));
        }

        // Snapshot free clusters before delete
        let stats_before = vol.stats().expect("stats before delete");

        // delete_recursive on the root of the tree
        vol.delete_recursive("/d1")
            .unwrap_or_else(|_| panic!("delete_recursive depth={}", depth));

        // Root directory should be empty
        let root = vol.read_root_directory().expect("read root");
        assert!(
            root.is_empty(),
            "root not empty after delete_recursive depth={}",
            depth
        );

        // All clusters should be freed
        let stats_after = vol.stats().expect("stats after delete");
        assert!(
            stats_after.free_clusters > stats_before.free_clusters,
            "clusters not freed after delete_recursive depth={}: before={}, after={}",
            depth,
            stats_before.free_clusters,
            stats_after.free_clusters
        );

        // Verify the deepest path is truly gone
        assert!(
            vol.resolve_path("/d1").is_err(),
            "/d1 still exists after delete_recursive depth={}",
            depth
        );
    }
}

/// Verify that delete_recursive on a tree with wide + deep branches works.
/// Simulates an Xbox game content directory: a parent with multiple subdirs,
/// each containing files.
#[test]
fn test_delete_recursive_wide_and_deep() {
    let (_tmp, mut vol) = common::create_fatx_image(8);

    // Create structure:
    //   /game/
    //     save1/ -> data.bin
    //     save2/ -> data.bin, meta.txt
    //     save3/
    //       sub/ -> deep.bin
    vol.create_directory("/game").expect("mkdir game");

    vol.create_directory("/game/save1").expect("mkdir save1");
    vol.create_file("/game/save1/data.bin", &[0xAA; 1024])
        .expect("create save1/data.bin");

    vol.create_directory("/game/save2").expect("mkdir save2");
    vol.create_file("/game/save2/data.bin", &[0xBB; 2048])
        .expect("create save2/data.bin");
    vol.create_file("/game/save2/meta.txt", b"save metadata")
        .expect("create save2/meta.txt");

    vol.create_directory("/game/save3").expect("mkdir save3");
    vol.create_directory("/game/save3/sub")
        .expect("mkdir save3/sub");
    vol.create_file("/game/save3/sub/deep.bin", &[0xCC; 512])
        .expect("create save3/sub/deep.bin");

    let stats_before = vol.stats().expect("stats");

    vol.delete_recursive("/game")
        .expect("delete_recursive /game");

    // Everything should be gone
    assert!(vol.resolve_path("/game").is_err());
    assert!(vol.read_root_directory().unwrap().is_empty());

    // Clusters freed
    let stats_after = vol.stats().expect("stats");
    assert!(stats_after.free_clusters > stats_before.free_clusters);
}

// ===========================================================================
// In-place file writes (write_file_in_place)
// ===========================================================================

/// Basic in-place write: overwrite a file with same-size data.
/// No cluster allocation or freeing needed — pure data overwrite.
#[test]
fn test_write_in_place_same_size() {
    let (_tmp, mut vol) = common::create_fatx_image(4);

    vol.create_file("/test.bin", &[0xAA; 1024]).expect("create");
    let stats_before = vol.stats().expect("stats");

    vol.write_file_in_place("/test.bin", &[0xBB; 1024])
        .expect("write in-place");

    let data = vol.read_file_by_path("/test.bin").expect("read");
    assert_eq!(data, vec![0xBB; 1024]);

    // No cluster changes — free count should be the same
    let stats_after = vol.stats().expect("stats");
    assert_eq!(stats_after.free_clusters, stats_before.free_clusters);
}

/// In-place write where file grows — must extend the cluster chain.
#[test]
fn test_write_in_place_file_grows() {
    let (_tmp, mut vol) = common::create_fatx_image(4);

    // Create a small file (1 cluster)
    vol.create_file("/grow.bin", &[0x11; 100]).expect("create");
    let stats_small = vol.stats().expect("stats");

    // Write much larger data (multiple clusters)
    let big_data = vec![0x22; 50000];
    vol.write_file_in_place("/grow.bin", &big_data)
        .expect("write in-place grow");

    let read_back = vol.read_file_by_path("/grow.bin").expect("read");
    assert_eq!(read_back, big_data);

    // Should have used more clusters
    let stats_big = vol.stats().expect("stats");
    assert!(stats_big.free_clusters < stats_small.free_clusters);
}

/// In-place write where file shrinks — must free excess clusters.
#[test]
fn test_write_in_place_file_shrinks() {
    let (_tmp, mut vol) = common::create_fatx_image(4);

    // Create a large file (multiple clusters)
    let big_data = vec![0x33; 50000];
    vol.create_file("/shrink.bin", &big_data).expect("create");
    let stats_big = vol.stats().expect("stats");

    // Overwrite with small data
    vol.write_file_in_place("/shrink.bin", &[0x44; 100])
        .expect("write in-place shrink");

    let read_back = vol.read_file_by_path("/shrink.bin").expect("read");
    assert_eq!(read_back, vec![0x44; 100]);

    // Should have freed clusters
    let stats_small = vol.stats().expect("stats");
    assert!(stats_small.free_clusters > stats_big.free_clusters);
}

/// In-place write updates the directory entry file_size correctly.
#[test]
fn test_write_in_place_updates_dirent_size() {
    let (_tmp, mut vol) = common::create_fatx_image(4);

    vol.create_file("/size.bin", &[0x55; 1000]).expect("create");

    // Verify initial size
    let entry = vol.resolve_path("/size.bin").expect("resolve");
    assert_eq!(entry.file_size, 1000);

    // Write larger data
    vol.write_file_in_place("/size.bin", &[0x66; 5000])
        .expect("write in-place");

    let entry = vol.resolve_path("/size.bin").expect("resolve after");
    assert_eq!(entry.file_size, 5000);

    // Write smaller data
    vol.write_file_in_place("/size.bin", &[0x77; 200])
        .expect("write in-place shrink");

    let entry = vol.resolve_path("/size.bin").expect("resolve after shrink");
    assert_eq!(entry.file_size, 200);
}

#[test]
fn test_read_chain_rejects_out_of_range_next_cluster() {
    let (_tmp, mut vol) = common::create_fatx_image(4);

    vol.create_file("/corrupt.bin", &[0xAA; 100])
        .expect("create");
    let entry = vol.resolve_path("/corrupt.bin").expect("resolve");
    let invalid_next = FIRST_CLUSTER + vol.total_clusters + 5;
    vol.write_fat_entry(entry.first_cluster, FatEntry::Next(invalid_next))
        .expect("corrupt fat entry");

    let result = vol.read_chain(entry.first_cluster);
    assert!(
        matches!(result, Err(FatxError::CorruptChain(c)) if c == entry.first_cluster),
        "expected corrupt chain for out-of-range next, got {:?}",
        result
    );
}

#[test]
fn test_read_chain_rejects_next_cluster_at_exact_upper_bound() {
    let (_tmp, mut vol) = common::create_fatx_image(4);

    vol.create_file("/boundary.bin", &[0xAB; 100])
        .expect("create");
    let entry = vol.resolve_path("/boundary.bin").expect("resolve");
    let invalid_next = FIRST_CLUSTER + vol.total_clusters;
    vol.write_fat_entry(entry.first_cluster, FatEntry::Next(invalid_next))
        .expect("corrupt fat entry");

    let result = vol.read_chain(entry.first_cluster);
    assert!(
        matches!(result, Err(FatxError::CorruptChain(c)) if c == entry.first_cluster),
        "expected corrupt chain for exact-boundary next, got {:?}",
        result
    );
}

#[test]
fn test_read_chain_rejects_cycle() {
    let (_tmp, mut vol) = common::create_fatx_image(4);

    let first = vol.allocate_chain(2).expect("allocate chain");
    let chain = vol.read_chain(first).expect("read allocated chain");
    assert_eq!(chain.len(), 2);

    vol.write_fat_entry(chain[1], FatEntry::Next(chain[0]))
        .expect("create cycle");

    let result = vol.read_chain(first);
    assert!(
        matches!(result, Err(FatxError::CorruptChain(c)) if c == chain[0] || c == chain[1]),
        "expected corrupt chain for cycle, got {:?}",
        result
    );
}

#[test]
fn test_write_in_place_refreshes_write_and_access_timestamps() {
    let (_tmp, mut vol) = common::create_fatx_image(4);

    vol.create_file("/timestamps.bin", &[0xAA; 128])
        .expect("create");
    let before = vol.resolve_path("/timestamps.bin").expect("resolve before");

    // FAT timestamps are stored with 2-second granularity.
    sleep(Duration::from_secs(2));

    vol.write_file_in_place("/timestamps.bin", &[0xBB; 128])
        .expect("overwrite");

    let after = vol.resolve_path("/timestamps.bin").expect("resolve after");
    assert_eq!(
        after.creation_date, before.creation_date,
        "overwrite should preserve creation date"
    );
    assert_eq!(
        after.creation_time, before.creation_time,
        "overwrite should preserve creation time"
    );
    assert_ne!(
        (after.write_date, after.write_time),
        (before.write_date, before.write_time),
        "overwrite should refresh write timestamp"
    );
    assert_ne!(
        (after.access_date, after.access_time),
        (before.access_date, before.access_time),
        "overwrite should refresh access timestamp"
    );
}

#[test]
fn test_create_or_replace_file_refreshes_timestamps() {
    let (_tmp, mut vol) = common::create_fatx_image(4);

    vol.create_file("/replace.bin", b"first").expect("create");
    let before = vol.resolve_path("/replace.bin").expect("resolve before");

    sleep(Duration::from_secs(2));

    vol.create_or_replace_file("/replace.bin", b"second")
        .expect("replace");

    let after = vol.resolve_path("/replace.bin").expect("resolve after");
    let data = vol.read_file_by_path("/replace.bin").expect("read");
    assert_eq!(data, b"second");
    assert_eq!(after.creation_date, before.creation_date);
    assert_eq!(after.creation_time, before.creation_time);
    assert_ne!(
        (after.write_date, after.write_time),
        (before.write_date, before.write_time),
        "replace helper should refresh write timestamp"
    );
}

/// Multiple in-place writes simulate the NFS flush cycle:
/// write, flush, write more, flush again.
#[test]
fn test_write_in_place_repeated_overwrites() {
    let (_tmp, mut vol) = common::create_fatx_image(4);

    vol.create_file("/cycle.bin", &[0x00; 100]).expect("create");

    // Simulate 10 flush cycles with growing data (like NFS buffered writes)
    for i in 1..=10u8 {
        let size = (i as usize) * 1000;
        let data = vec![i; size];
        vol.write_file_in_place("/cycle.bin", &data)
            .unwrap_or_else(|_| panic!("write cycle {}", i));

        let read_back = vol.read_file_by_path("/cycle.bin").expect("read");
        assert_eq!(read_back.len(), size);
        assert_eq!(read_back[0], i);
        assert_eq!(read_back[size - 1], i);
    }
}

/// In-place write on a file in a subdirectory.
#[test]
fn test_write_in_place_subdirectory() {
    let (_tmp, mut vol) = common::create_fatx_image(4);

    vol.create_directory("/Content").expect("mkdir");
    vol.create_directory("/Content/Game").expect("mkdir game");
    vol.create_file("/Content/Game/save.dat", &[0xAA; 2048])
        .expect("create");

    vol.write_file_in_place("/Content/Game/save.dat", &[0xBB; 4096])
        .expect("write in-place subdir");

    let data = vol
        .read_file_by_path("/Content/Game/save.dat")
        .expect("read");
    assert_eq!(data, vec![0xBB; 4096]);
}

/// In-place write on nonexistent file should return FileNotFound.
#[test]
fn test_write_in_place_nonexistent_fails() {
    let (_tmp, mut vol) = common::create_fatx_image(2);

    let result = vol.write_file_in_place("/nope.bin", &[0xFF; 100]);
    assert!(result.is_err());
}

#[test]
fn test_begin_write_in_place_partial_extension_write_does_not_publish_size() {
    let (tmp, mut vol) = common::create_fatx_image(4);

    let original = vec![0x21; 100];
    vol.create_file("/session-grow.bin", &original)
        .expect("create");

    let cluster_size = vol.superblock.cluster_size() as usize;
    let first_cluster = vol
        .resolve_path("/session-grow.bin")
        .expect("resolve grow session file")
        .first_cluster;
    let session = vol
        .begin_write_in_place_for_entry(FIRST_CLUSTER, first_cluster, cluster_size * 5)
        .expect("begin session");
    assert_eq!(
        session.clusters().len(),
        5,
        "grow session should reserve target chain"
    );

    let extension_cluster = session.clusters()[1];
    let extension_payload = vec![0x7A; cluster_size];
    vol.write_cluster(extension_cluster, &extension_payload)
        .expect("write extension cluster");
    vol.flush().expect("flush uncommitted session");

    let image = std::fs::OpenOptions::new()
        .read(true)
        .write(true)
        .open(common::image_path(&tmp))
        .expect("reopen image");
    let mut reopened = FatxVolume::open(image, 0, 0).expect("open volume");

    let entry = reopened
        .resolve_path("/session-grow.bin")
        .expect("resolve after partial write");
    assert_eq!(
        entry.file_size,
        original.len() as u32,
        "session writes must not publish a larger file size before commit"
    );
    assert_eq!(
        reopened
            .read_file_by_path("/session-grow.bin")
            .expect("read after partial write"),
        original
    );
    drop(reopened);

    vol.cancel_write_session(session).expect("cancel session");
    vol.flush().expect("flush cancel");
}

#[test]
fn test_cancel_write_session_releases_extension_and_preserves_visible_file() {
    let (tmp, mut vol) = common::create_fatx_image(4);

    let original = vec![0x44; 100];
    vol.create_file("/session-cancel.bin", &original)
        .expect("create");
    let before = vol.stats().expect("stats before");

    let cluster_size = vol.superblock.cluster_size() as usize;
    let first_cluster = vol
        .resolve_path("/session-cancel.bin")
        .expect("resolve cancel session file")
        .first_cluster;
    let session = vol
        .begin_write_in_place_for_entry(FIRST_CLUSTER, first_cluster, cluster_size * 4)
        .expect("begin session");
    let extension_cluster = session.clusters()[1];
    vol.write_cluster(extension_cluster, &vec![0x55; cluster_size])
        .expect("write extension cluster");
    vol.flush().expect("flush uncommitted session");

    vol.cancel_write_session(session).expect("cancel session");
    vol.flush().expect("flush cancel");
    drop(vol);

    let image = std::fs::OpenOptions::new()
        .read(true)
        .write(true)
        .open(common::image_path(&tmp))
        .expect("reopen image");
    let mut reopened = FatxVolume::open(image, 0, 0).expect("open volume");

    let entry = reopened
        .resolve_path("/session-cancel.bin")
        .expect("resolve after cancel");
    assert_eq!(entry.file_size, original.len() as u32);
    assert_eq!(
        reopened
            .read_file_by_path("/session-cancel.bin")
            .expect("read after cancel"),
        original
    );

    let after = reopened.stats().expect("stats after");
    assert_eq!(
        after.free_clusters, before.free_clusters,
        "cancelling a grow session should release reserved extension clusters"
    );
}

// ===========================================================================
// copy_from_host bugs
// ===========================================================================

/// Trailing slash means "treat --to as the parent and append the source dir name".
#[test]
fn test_copy_from_host_trailing_slash_appends_dir_name() {
    let (_tmp, mut vol) = common::create_fatx_image(4);

    let local_tmp = tempfile::TempDir::new().unwrap();
    let src = local_tmp.path().join("ABCDEFG");
    std::fs::create_dir(&src).unwrap();
    std::fs::write(src.join("file1.bin"), b"hello").unwrap();

    vol.create_directory("/dest").expect("mkdir dest");
    vol.copy_from_host(&src, "/dest/", None).expect("copy");

    let dest_cluster = vol.resolve_path("/dest").unwrap().first_cluster;
    let dest_entries = vol.read_directory(dest_cluster).unwrap();
    let names: Vec<String> = dest_entries.iter().map(|e| e.filename()).collect();

    assert!(
        names.contains(&"ABCDEFG".to_string()),
        "trailing slash should append source dir name. Got: {:?}",
        names
    );
    let nested = vol.resolve_path("/dest/ABCDEFG/file1.bin");
    assert!(
        nested.is_ok(),
        "nested file should exist under appended dir"
    );
}

/// Root destinations should stay rooted when the trailing-slash convention
/// appends the source directory name.
#[test]
fn test_copy_from_host_trailing_slash_root() {
    let (_tmp, mut vol) = common::create_fatx_image(4);

    let local_tmp = tempfile::TempDir::new().unwrap();
    let src = local_tmp.path().join("rootsrc");
    std::fs::create_dir(&src).unwrap();
    std::fs::write(src.join("test.txt"), b"data").unwrap();

    vol.copy_from_host(&src, "/", None).expect("copy");
    let result = vol.resolve_path("/rootsrc/test.txt");
    assert!(
        result.is_ok(),
        "root trailing slash should create /rootsrc/test.txt. Got: {:?}",
        result.err()
    );
}

#[test]
fn test_create_file_rejects_duplicate_name() {
    let (_tmp, mut vol) = common::create_fatx_image(4);

    vol.create_file("/dup.bin", b"first").expect("create first");
    let result = vol.create_file("/dup.bin", b"second");
    assert!(matches!(result, Err(FatxError::FileExists(ref path)) if path == "/dup.bin"));

    let entries = vol.read_directory(FIRST_CLUSTER).unwrap();
    let dup_count = entries.iter().filter(|e| e.filename() == "dup.bin").count();
    assert_eq!(
        dup_count, 1,
        "duplicate create should not add a second entry"
    );

    let data = vol.read_file_by_path("/dup.bin").unwrap();
    assert_eq!(data, b"first", "original file should be preserved");
}

#[test]
fn test_copy_from_host_recopy_fails_on_duplicate() {
    let (_tmp, mut vol) = common::create_fatx_image(4);

    let local_tmp = tempfile::TempDir::new().unwrap();
    let src = local_tmp.path().join("src");
    std::fs::create_dir(&src).unwrap();
    std::fs::write(src.join("file.bin"), b"original").unwrap();

    vol.copy_from_host(&src, "/dest", None).expect("first copy");
    let result = vol.copy_from_host(&src, "/dest", None);
    assert!(
        matches!(result, Err(FatxError::FileExists(ref path)) if path == "/dest/file.bin"),
        "second copy should fail on the existing child file, got: {:?}",
        result
    );

    let dest = vol.resolve_path("/dest").unwrap();
    let entries = vol.read_directory(dest.first_cluster).unwrap();
    let file_count = entries
        .iter()
        .filter(|e| e.filename() == "file.bin")
        .count();
    assert_eq!(
        file_count, 1,
        "re-copy should not create duplicate directory entries"
    );
}

#[test]
fn test_copy_from_host_no_slash_copies_contents_into_target_dir() {
    let (_tmp, mut vol) = common::create_fatx_image(4);

    let local_tmp = tempfile::TempDir::new().unwrap();
    let src = local_tmp.path().join("ABCDEFG");
    std::fs::create_dir(&src).unwrap();
    std::fs::write(src.join("file.bin"), b"payload").unwrap();

    vol.create_directory("/dest").expect("mkdir dest");
    vol.copy_from_host(&src, "/dest/ABCDEFG", None)
        .expect("copy");

    assert!(vol.resolve_path("/dest/ABCDEFG/file.bin").is_ok());
}

#[test]
fn test_create_file_rejects_name_matching_directory() {
    let (_tmp, mut vol) = common::create_fatx_image(4);

    vol.create_directory("/stuff").expect("mkdir");
    let result = vol.create_file("/stuff", b"oops");
    assert!(
        matches!(result, Err(FatxError::FileExists(ref path)) if path == "/stuff"),
        "create_file should reject a name that already belongs to a directory"
    );

    let entries = vol.read_directory(FIRST_CLUSTER).unwrap();
    let stuff_entries: Vec<_> = entries.iter().filter(|e| e.filename() == "stuff").collect();
    assert_eq!(
        stuff_entries.len(),
        1,
        "directory entry should remain unique after failed create"
    );
    assert!(stuff_entries[0].is_directory());
}

#[test]
fn test_create_file_frees_allocated_clusters_on_dirent_write_failure() {
    let (tmp, vol) = common::create_fatx_image(4);
    let img_path = common::image_path(&tmp);
    drop(vol);

    let image_bytes = std::fs::read(&img_path).expect("read image bytes");
    let state = Rc::new(RefCell::new(FailingWriteState::default()));
    let cursor = FailingWriteCursor {
        inner: Cursor::new(image_bytes),
        state: Rc::clone(&state),
    };
    let mut vol = FatxVolume::open(cursor, 0, 0).expect("open with failing cursor");

    let stats_before = vol.stats().expect("stats before");
    // write #1 initializes the new directory cluster; write #2 persists the
    // parent directory entry, which is the rollback edge we want here.
    state.borrow_mut().fail_on_write = Some(2);

    let result = vol.create_file("/leak.bin", b"abc");
    assert!(
        result.is_err(),
        "injected write failure should abort create"
    );

    let stats_after = vol.stats().expect("stats after");
    assert_eq!(
        stats_after.free_clusters, stats_before.free_clusters,
        "failed create should free the allocated chain"
    );
    assert!(
        matches!(
            vol.resolve_path("/leak.bin"),
            Err(FatxError::FileNotFound(_))
        ),
        "failed create should not leave a reachable directory entry"
    );
}

#[test]
fn test_create_directory_frees_allocated_cluster_on_dirent_write_failure() {
    let (tmp, vol) = common::create_fatx_image(4);
    let img_path = common::image_path(&tmp);
    drop(vol);

    let image_bytes = std::fs::read(&img_path).expect("read image bytes");
    let state = Rc::new(RefCell::new(FailingWriteState::default()));
    let cursor = FailingWriteCursor {
        inner: Cursor::new(image_bytes),
        state: Rc::clone(&state),
    };
    let mut vol = FatxVolume::open(cursor, 0, 0).expect("open with failing cursor");

    let stats_before = vol.stats().expect("stats before");
    state.borrow_mut().fail_on_write = Some(2);

    let result = vol.create_directory("/broken");
    assert!(
        result.is_err(),
        "injected write failure should abort directory create"
    );

    let stats_after = vol.stats().expect("stats after");
    assert_eq!(
        stats_after.free_clusters, stats_before.free_clusters,
        "failed mkdir should free the allocated directory cluster"
    );
    assert!(
        matches!(vol.resolve_path("/broken"), Err(FatxError::FileNotFound(_))),
        "failed mkdir should not leave a reachable directory entry"
    );
}

#[test]
fn test_directory_growth_failure_rolls_back_new_parent_cluster() {
    let (tmp, mut vol) = common::create_fatx_image(8);

    vol.create_directory("/full").expect("mkdir");
    for i in 0..256 {
        let name = format!("/full/f{:03}.bin", i);
        vol.create_file(&name, &[i as u8]).expect("fill full dir");
    }
    let parent_cluster = vol
        .resolve_path("/full")
        .expect("resolve full")
        .first_cluster;
    let parent_chain_before = vol.read_chain(parent_cluster).expect("parent chain before");
    let stats_before = vol.stats().expect("stats before");
    vol.flush().expect("flush populated image");

    let img_path = common::image_path(&tmp);
    drop(vol);

    let image_bytes = std::fs::read(&img_path).expect("read image bytes");
    let state = Rc::new(RefCell::new(FailingWriteState::default()));
    let cursor = FailingWriteCursor {
        inner: Cursor::new(image_bytes),
        state: Rc::clone(&state),
    };
    let mut vol = FatxVolume::open(cursor, 0, 0).expect("open with failing cursor");
    state.borrow_mut().fail_on_write = Some(2);

    let result = vol.create_file("/full/overflow.bin", b"x");
    assert!(
        result.is_err(),
        "injected write failure should abort create in expanded dir"
    );

    let stats_after = vol.stats().expect("stats after");
    assert_eq!(
        stats_after.free_clusters, stats_before.free_clusters,
        "failed directory expansion should free both file data and parent dir clusters"
    );
    assert_eq!(
        vol.read_chain(parent_cluster).expect("parent chain after"),
        parent_chain_before,
        "failed directory expansion should restore the parent directory chain"
    );
    assert!(
        matches!(
            vol.resolve_path("/full/overflow.bin"),
            Err(FatxError::FileNotFound(_))
        ),
        "failed create should not leave a reachable directory entry"
    );
}

#[test]
fn test_copy_from_host_stale_file_blocks_directory() {
    let (_tmp, mut vol) = common::create_fatx_image(4);

    let local_tmp = tempfile::TempDir::new().unwrap();
    let src = local_tmp.path().join("ABCDEFG");
    std::fs::create_dir(&src).unwrap();
    std::fs::write(src.join("file1.bin"), b"hello").unwrap();

    vol.create_directory("/dest").expect("mkdir dest");
    vol.create_file("/dest/ABCDEFG", b"stale data")
        .expect("create stale file");

    let result = vol.copy_from_host(&src, "/dest/ABCDEFG", None);
    assert!(
        matches!(result, Err(FatxError::NotADirectory(ref path)) if path == "/dest/ABCDEFG"),
        "stale file should be rejected as not-a-directory, got: {:?}",
        result
    );

    let dest_cluster = vol.resolve_path("/dest").unwrap().first_cluster;
    let entries = vol.read_directory(dest_cluster).unwrap();
    let abcdefg: Vec<_> = entries
        .iter()
        .filter(|e| e.filename() == "ABCDEFG")
        .collect();
    assert_eq!(abcdefg.len(), 1, "only one ABCDEFG entry");
    assert!(
        !abcdefg[0].is_directory(),
        "stale blocking entry should remain a file"
    );
}

#[test]
fn test_create_file_after_delete_reuses_name() {
    let (_tmp, mut vol) = common::create_fatx_image(4);

    vol.create_file("/reuse.bin", b"first")
        .expect("create first");
    vol.delete("/reuse.bin").expect("delete");
    vol.create_file("/reuse.bin", b"second")
        .expect("create second");

    let data = vol.read_file_by_path("/reuse.bin").expect("read");
    assert_eq!(data, b"second");
}

// ===========================================================================
// macOS metadata filtering
// ===========================================================================

#[test]
fn test_copy_from_host_skips_macos_metadata() {
    let (_tmp, mut vol) = common::create_fatx_image(4);

    let local_tmp = tempfile::TempDir::new().unwrap();
    let src = local_tmp.path().join("src");
    std::fs::create_dir(&src).unwrap();
    std::fs::write(src.join("game.bin"), b"real file").unwrap();
    std::fs::write(src.join(".DS_Store"), b"macos junk").unwrap();
    std::fs::write(src.join("._game.bin"), b"resource fork").unwrap();
    std::fs::create_dir(src.join(".Spotlight-V100")).unwrap();
    std::fs::write(src.join(".Spotlight-V100").join("index"), b"idx").unwrap();
    std::fs::create_dir(src.join(".Trashes")).unwrap();
    std::fs::create_dir(src.join(".fseventsd")).unwrap();

    vol.copy_from_host(&src, "/dest", None).expect("copy");

    let dest = vol.resolve_path("/dest").unwrap();
    let entries = vol.read_directory(dest.first_cluster).unwrap();
    let names: Vec<String> = entries.iter().map(|e| e.filename()).collect();

    assert_eq!(
        names,
        vec!["game.bin"],
        "only real files should be copied, got: {:?}",
        names
    );
}

#[test]
fn test_is_macos_metadata() {
    use fatxlib::types::is_macos_metadata;

    assert!(is_macos_metadata(".DS_Store"));
    assert!(is_macos_metadata(".Spotlight-V100"));
    assert!(is_macos_metadata(".Trashes"));
    assert!(is_macos_metadata(".fseventsd"));
    assert!(is_macos_metadata("._anything"));
    assert!(is_macos_metadata("._Icon\r"));
    assert!(is_macos_metadata("._"));

    assert!(!is_macos_metadata("game.bin"));
    assert!(!is_macos_metadata("Content"));
    assert!(!is_macos_metadata(".hidden"));
    assert!(!is_macos_metadata("DS_Store"));
}

#[test]
fn test_scan_and_delete_macos_metadata() {
    let (_tmp, mut vol) = common::create_fatx_image(4);

    vol.create_directory("/Content").expect("mkdir");
    vol.create_file("/Content/game.bin", b"real data")
        .expect("create game");
    vol.create_file("/Content/.DS_Store", b"junk")
        .expect("create ds_store");
    vol.create_file("/Content/._game.bin", b"resource fork")
        .expect("create resource");
    vol.create_file("/.DS_Store", b"root junk")
        .expect("create root ds_store");

    let found = vol.scan_macos_metadata().expect("scan");
    assert_eq!(found.len(), 3, "should find 3 metadata entries");

    let (files, dirs, bytes) = vol.delete_macos_metadata(&found, None).expect("delete");
    assert_eq!(files, 3);
    assert_eq!(dirs, 0);
    assert!(bytes > 0);

    assert!(vol.resolve_path("/Content/game.bin").is_ok());
    assert!(vol.resolve_path("/Content/.DS_Store").is_err());
    assert!(vol.resolve_path("/Content/._game.bin").is_err());
    assert!(vol.resolve_path("/.DS_Store").is_err());
}

#[test]
fn test_scan_macos_metadata_empty_volume() {
    let (_tmp, mut vol) = common::create_fatx_image(2);
    vol.create_file("/game.bin", b"data").expect("create");
    let found = vol.scan_macos_metadata().expect("scan");
    assert!(found.is_empty());
}
